=== JosePina98/PinaGomez-JoseAntonio-arso-laboratorio/Practica-1/xml_ejercicio1/esquema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/esquema"
	xmlns:tns="http://www.example.org/esquema"
	elementFormDefault="qualified">
	
	<simpleType name="tipo_nota">
		<restriction base="integer">
			<minInclusive value="0"/>
			<maxInclusive value="10"/>
		</restriction>		
	</simpleType>
	
	<simpleType name="tipo_extraordinaria">
		<restriction base="string">
			<enumeration value="si"/>
			<enumeration value="no"/>
		</restriction>
	</simpleType>
	
	<simpleType name="tipo_convocatoria">
		<restriction base="string">
			<enumeration value="febrero"/>
			<enumeration value="junio"/>
			<enumeration value="julio"/>
		</restriction>
	</simpleType>
	
	<simpleType name="tipo_curso">
		<restriction base="string">
			<pattern value="[1-9]"/>
		</restriction>
	</simpleType>
	
	<complexType name="tipo_calificacion">
		<attribute name="nif" type="string" use="required"/>
		<attribute name="nombre" type="string"/>
		<attribute name="nota" type="tns:tipo_nota" use="required"/>
	</complexType>
	
	<complexType name="tipo_diligencia">
		<attribute name="nif" type="string" use="required"/>
		<attribute name="nombre" type="string"/>
		<attribute name="nota" type="tns:tipo_nota" use="required"/>
		<attribute name="fecha" type="date" use="required"/>
		<attribute name="extraordinaria" type="tns:tipo_extraordinaria" default="no"/>
	</complexType>
					
	<element name="documento">
		<complexType>
			<sequence>
				<element name="calificacion" type="tns:tipo_calificacion" minOccurs="1" maxOccurs="unbounded"/>
				<element name="diligencia" type="tns:tipo_diligencia" minOccurs="0" maxOccurs="unbounded"/>
			</sequence>
			<attribute name="asignatura" type="string" use="required"/>
			<attribute name="convocatoria" type="tns:tipo_convocatoria" use="required"/>
			<attribute name="curso" type="tns:tipo_curso"/>
		</complexType>
	</element>
</schema>

=== JosePina98/PinaGomez-JoseAntonio-arso-laboratorio/Practica-2/xml_ejercicios_DOM/prueba.xml
<?xml version="1.0" encoding="UTF-8"?>
<documento asignatura="DAWEB" convocatoria="febrero" curso="1"
	xmlns="http://www.example.org/esquema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/esquema esquema.xsd ">
	
	
	<calificacion nif="1111111A" nombre="Jose" nota="5"/>
	<calificacion nif="222222A" nota="0"/>
	<calificacion nif="222222A" nota="10"/>
	<calificacion nif="222222A" nota="9.5"/>
	
	<diligencia 
		nif="111111A"
		nombre="Jose"
		nota="10"
		fecha="2020-01-18"
		extraordinaria="no"/>
	
	<diligencia 
		nif="222222A"
		nota="10"
		fecha="2020-01-19"/>
		
	<diligencia 
		nif="111111A"
		nombre="Jose"
		nota="10"
		fecha="2020-01-02"
		extraordinaria="no"/>
	
	<diligencia 
		nif="222222A"
		nota="10"
		fecha="2020-01-22"/>
</documento>

=== JosePina98/PinaGomez-JoseAntonio-arso-laboratorio/Practica-2/xml_ejercicios_DOM/pruebaModificada.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><documento xmlns="http://www.example.org/esquema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" asignatura="DAWEB" convocatoria="febrero" curso="1" xsi:schemaLocation="http://www.example.org/esquema esquema.xsd ">
	
	
	<calificacion nif="1111111A" nombre="Jose" nota="5.5"/>
	<calificacion nif="222222A" nota="0.5"/>
	<calificacion nif="222222A" nota="10"/>
	<calificacion nif="222222A" nota="10.0"/>
	
	<diligencia extraordinaria="no" fecha="2020-01-18" nif="111111A" nombre="Jose" nota="10"/>
	
	<diligencia fecha="2020-01-19" nif="222222A" nota="10"/>
		
	<diligencia extraordinaria="no" fecha="2020-01-02" nif="111111A" nombre="Jose" nota="10"/>
	
	<diligencia fecha="2020-01-22" nif="222222A" nota="10"/>
</documento>
